language: ruby
rvm:
  - 2.3.3
  - 2.4.0
  - 2.5.0
  - 2.6.0

before_script:
  - cd spec/dummy && bundle exec rake railties:install:migrations
  - RAILS_ENV=test bundle exec rake db:migrate
  - cd ../..

script: 'bundle exec rspec'

cache: bundler

notifications:
  recipients:
    - deepakmahakale@gmail.com
